- hosts: all
  vars:
    service_name: libraryservice
    github_repo: git@github.com:TangentMicroServices/LibraryService.git
    service_http_port: 8011
    service_db_password: testtest    
    
  vars_files:
    - vars/main.yml

  roles:
    - Ansibles.postgresql
    - toast38coza.djangoserver
 
  tasks:
    - include: 'tasks/main.yml'
